version: "2.1"
services:
    musig:
        image: arkecosystem/musig-server
        container_name: musig-test
        restart: always
        ports:
            - "${PORT:-3334}:${PORT:-3334}"
        cap_add:
            - SYS_NICE
            - SYS_RESOURCE
            - SYS_TIME
        volumes:
            - ~/.musig-test:/home/node/.local
        networks:
            - musig-test
        environment:
            - MODE=${MODE:-test}
            - COIN=${COIN:-ark}
        tty: true
volumes:
    musig-test:
networks:
    musig-test:
